# Site settings
title: Analog Portal
version: "v1"
description: "Static template for Analog Customer Portal front-end"

# Tachyons Version
tv: "4.5.5"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]
